In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler , StandardScaler, Normalizer, Binarizer

In [8]:
df = pd.read_csv("C:/Users/Administrator/Downloads/winequality-red.csv",usecols = ['fixed acidity','residual sugar'])

In [9]:
df.head()

   fixed acidity  residual sugar
0            7.4             1.9
1            7.8             2.6
2            7.8             2.3
3           11.2             1.9
4            7.4             1.9

In [10]:
usecols = ['fixed acidity','residual sugar']

In [11]:
df.describe()

       fixed acidity  residual sugar
count    1599.000000     1599.000000
mean        8.319637        2.538806
std         1.741096        1.409928
min         4.600000        0.900000
25%         7.100000        1.900000
50%         7.900000        2.200000
75%         9.200000        2.600000
max        15.900000       15.500000

In [15]:
m_scaler = MinMaxScaler()
scaled_data = m_scaler.fit_transform(df.dropna())
scaled_data

array([[0.24778761, 0.06849315],
       [0.28318584, 0.11643836],
       [0.28318584, 0.09589041],
       ...,
       [0.15044248, 0.09589041],
       [0.11504425, 0.07534247],
       [0.12389381, 0.18493151]], shape=(1599, 2))

In [16]:
s_scaler = StandardScaler()
scaled_data = s_scaler.fit_transform(df.dropna())
scaled_data

array([[-0.52835961, -0.45321841],
       [-0.29854743,  0.04341614],
       [-0.29854743, -0.16942723],
       ...,
       [-1.1603431 , -0.16942723],
       [-1.39015528, -0.38227061],
       [-1.33270223,  0.75289408]], shape=(1599, 2))

In [17]:
normalizer = Normalizer()
scaled_data = normalizer.fit_transform(df.dropna())
scaled_data

array([[0.96858307, 0.24869025],
       [0.9486833 , 0.31622777],
       [0.95916946, 0.28283202],
       ...,
       [0.93935732, 0.34293997],
       [0.94706588, 0.32103928],
       [0.85749293, 0.51449576]], shape=(1599, 2))

In [18]:
binarizer = Binarizer()
scaled_data = binarizer.fit_transform(df.dropna())
scaled_data

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [1., 1.]], shape=(1599, 2))